stages:
  - docker_build_validate
  - docker_build_push

docker_build_validate:
  stage: docker_build_validate
  tags:
    - docker
  script:
    - git clone https://github.com/NoxInmortus/docker-maniacontrol.git
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - docker buildx build -t albanosdes/docker-maniacontrol --platform=linux/arm,linux/arm64,linux/amd64 docker-maniacontrol/.
  only:
    - merge_requests

docker_build_push:
  stage: docker_build_push
  tags:
    - docker
  script:
    - git clone https://github.com/NoxInmortus/docker-maniacontrol.git
    - version=$(grep 'Version' docker-maniacontrol/README.md | awk -F ' ' '{ print $NF }')
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USER} --password-stdin
    - docker buildx build -t albanosdes/docker-maniacontrol:latest -t albanosdes/docker-maniacontrol:${version} --platform=linux/arm,linux/arm64,linux/amd64 docker-maniacontrol/. --push
  only:
    refs:
      - master
